### PR TITLE
Single particle metadata

### PR DESCRIPTION
**Pull request by alisterburt**
minimal metadata capture for single particle experiments into a relion format STAR file

### CODE REVIEW

**Comment by alisterburt** [comment]
okay cool, this is now working and producing a metadata file specified in a config file as follows

```yaml
cluster:
    max_workers: 1
    method: null
device: gpu
microscope:
    beam:
        acceleration_voltage_spread: 8.0e-07
        drift:
            magnitude: 0
            type: null
        electrons_per_angstrom: 30
        energy: 300
        energy_spread: 2.66e-06
        source_spread: 0.1
    detector:
        dqe: false
        nx: 512
        ny: 512
        origin:
        - 256
        - 256
        pixel_size: 1
    model: null
    objective_lens:
        c_10: -20000
        c_12: 0.0
        c_21: 0.0
        c_23: 0.0
        c_30: 2.7
        c_32: 0.0
        c_34: 0.0
        c_41: 0.0
        c_43: 0.0
        c_45: 0.0
        c_50: 0.0
        c_52: 0.0
        c_54: 0.0
        c_56: 0.0
        c_c: 2.7
        current_spread: 3.3e-07
        inner_aper_ang: 0.0
        m: 0
        outer_aper_ang: 0.0
        phi_12: 0.0
        phi_21: 0.0
        phi_23: 0.0
        phi_32: 0.0
        phi_34: 0.0
        phi_41: 0.0
        phi_43: 0.0
        phi_45: 0.0
        phi_52: 0.0
        phi_54: 0.0
        phi_56: 0.0
    phase_plate: false
sample:
    box:
    - 1024
    - 1024
    - 1024
    centre:
    - 512
    - 512
    - 512
    coords:
        filename: 6vxx.pdb
        recentre: true
    ice:
        density: 940
        generate: false
    shape:
        type: cube
        cube:
            length: 1024
    sputter:
        element: null
        thickness: 20
scan:
    mode: single_particle
    metadata_file: metadata_test.star
    num_images: 10
simulation:
    division_thickness: 100
    ice: true
    inelastic_model: null
    margin: 100
    mp_loss_position: peak
    mp_loss_width: null
    padding: 100
    radiation_damage_model: false
    sensitivity_coefficient: 0.014
    slice_thickness: 3.0
```

I'm managing to simulate images with the following script

```sh
parakeet.sample.new -c config_single_particle.yaml
parakeet.simulate.exit_wave -c config_single_particle.yaml
parakeet.simulate.optics -c config_single_particle.yaml
parakeet.simulate.image -c config_single_particle.yaml
parakeet.export image.h5 -o file.mrc
```

and a metadata file containing euler angles is produced

```sh
# Created by the starfile Python package (version 0.4.7) at 16:18:09 on 15/09/2021

data_

loop_
_rlnAngleRot #1
_rlnAngleTilt #2
_rlnAnglePsi #3
98.108720       72.698204       112.479366
-150.248180     79.420338       -97.452708
171.708782      76.407354       146.937079
43.054567       65.910080       39.277214
-43.502905      74.858533       -70.388246
-28.992185      110.440804      137.302435
26.484985       85.339273       -157.623764
98.885411       34.732470       -120.569440
-87.986549      52.744228       42.944251
143.618096      77.672831       -7.980060
```

**Comment by jmp1985** [comment]
Ok, so I've pulled your latest changes and merged them into the branch and run all the tests and everything seems to work for me. If you pull the latest changes and you are happy that this now does everything you need then I will go ahead and merge the pull request!

**Comment by jmp1985** [comment]
I have merged the branch now. One thing I forgot to ask is that the starfile.write function I have does not have the overwrite keyword but the source on master does (https://github.com/alisterburt/starfile/blob/master/starfile/functions.py). Does the version of the library on pypi need to be updated to get this keyword?

**Comment by alisterburt** [comment]
@jmp1985 hmm that was added quite a while ago - are you by any chance running on python 3.6?

try a quick `pip install --upgrade starfile` and `pip show starfile`, I'm on `0.4.7` here but I think overwrite has been in for the whole `0.4.X` series

**Comment by jmp1985** [comment]
@alisterburt I'm currently running on python3.9 on my laptop and it seems I was running with starfile version 0.111!

Not sure what happened, but when I tried to update the package it just said dependency satisfied and did nothing but removing and reinstalling the package seems to bring me up to date!

**Comment by alisterburt** [comment]
Aaah, I did yank this release but the fact that it doesn't respect Semver is still probably the cause of this, sorry about that!

**Pull request merged**
